# Generated by Django 5.0.4 on 2024-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('Description', models.TextField(max_length=1000)),
                ('Price', models.DecimalField(decimal_places=2, default=99.99, max_digits=15)),
                ('QauntityInStock', models.IntegerField()),
            ],
        ),
    ]
